/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BusinessLoginRouteImport } from './routes/business.login'
import { Route as BusinessSignupRouteImport } from './routes/business.signup'
import { Route as CreatorDashboardRouteImport } from './routes/creator.dashboard'
import { Route as CreatorLoginRouteImport } from './routes/creator.login'
import { Route as CreatorPlansRouteImport } from './routes/creator.plans'
import { Route as CreatorRegisterRouteImport } from './routes/creator.register'
import { Route as CreatorsCreatorIdRouteImport } from './routes/creators.$creatorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLoginRoute = BusinessLoginRouteImport.update({
  id: '/business/login',
  path: '/business/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSignupRoute = BusinessSignupRouteImport.update({
  id: '/business/signup',
  path: '/business/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: '/creator/dashboard',
  path: '/creator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorLoginRoute = CreatorLoginRouteImport.update({
  id: '/creator/login',
  path: '/creator/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorPlansRoute = CreatorPlansRouteImport.update({
  id: '/creator/plans',
  path: '/creator/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRegisterRoute = CreatorRegisterRouteImport.update({
  id: '/creator/register',
  path: '/creator/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsCreatorIdRoute = CreatorsCreatorIdRouteImport.update({
  id: '/creators/$creatorId',
  path: '/creators/$creatorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/signup': typeof BusinessSignupRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/creator/login': typeof CreatorLoginRoute
  '/creator/plans': typeof CreatorPlansRoute
  '/creator/register': typeof CreatorRegisterRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/signup': typeof BusinessSignupRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/creator/login': typeof CreatorLoginRoute
  '/creator/plans': typeof CreatorPlansRoute
  '/creator/register': typeof CreatorRegisterRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/signup': typeof BusinessSignupRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/creator/login': typeof CreatorLoginRoute
  '/creator/plans': typeof CreatorPlansRoute
  '/creator/register': typeof CreatorRegisterRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/discover'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/business/login'
    | '/business/signup'
    | '/creator/dashboard'
    | '/creator/login'
    | '/creator/plans'
    | '/creator/register'
    | '/creators/$creatorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/discover'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/business/login'
    | '/business/signup'
    | '/creator/dashboard'
    | '/creator/login'
    | '/creator/plans'
    | '/creator/register'
    | '/creators/$creatorId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/discover'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/business/login'
    | '/business/signup'
    | '/creator/dashboard'
    | '/creator/login'
    | '/creator/plans'
    | '/creator/register'
    | '/creators/$creatorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  BusinessLoginRoute: typeof BusinessLoginRoute
  BusinessSignupRoute: typeof BusinessSignupRoute
  CreatorDashboardRoute: typeof CreatorDashboardRoute
  CreatorLoginRoute: typeof CreatorLoginRoute
  CreatorPlansRoute: typeof CreatorPlansRoute
  CreatorRegisterRoute: typeof CreatorRegisterRoute
  CreatorsCreatorIdRoute: typeof CreatorsCreatorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/login': {
      id: '/business/login'
      path: '/business/login'
      fullPath: '/business/login'
      preLoaderRoute: typeof BusinessLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/signup': {
      id: '/business/signup'
      path: '/business/signup'
      fullPath: '/business/signup'
      preLoaderRoute: typeof BusinessSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/dashboard': {
      id: '/creator/dashboard'
      path: '/creator/dashboard'
      fullPath: '/creator/dashboard'
      preLoaderRoute: typeof CreatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/login': {
      id: '/creator/login'
      path: '/creator/login'
      fullPath: '/creator/login'
      preLoaderRoute: typeof CreatorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/plans': {
      id: '/creator/plans'
      path: '/creator/plans'
      fullPath: '/creator/plans'
      preLoaderRoute: typeof CreatorPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/register': {
      id: '/creator/register'
      path: '/creator/register'
      fullPath: '/creator/register'
      preLoaderRoute: typeof CreatorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$creatorId': {
      id: '/creators/$creatorId'
      path: '/creators/$creatorId'
      fullPath: '/creators/$creatorId'
      preLoaderRoute: typeof CreatorsCreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  BusinessLoginRoute: BusinessLoginRoute,
  BusinessSignupRoute: BusinessSignupRoute,
  CreatorDashboardRoute: CreatorDashboardRoute,
  CreatorLoginRoute: CreatorLoginRoute,
  CreatorPlansRoute: CreatorPlansRoute,
  CreatorRegisterRoute: CreatorRegisterRoute,
  CreatorsCreatorIdRoute: CreatorsCreatorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
